<a href="https://colab.research.google.com/github/jmuryawan/nhanes_inferential_2023./blob/main/nhanes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NHANES 2021-2023 Analysis

## Loading in Files

In [ ]:
# Load in Files â€“ Demographics

import pandas as pd

demographic_path = 'DEMO_L.XPT'
demo = pd.read_sas(demographic_path, format='xport') #, encoding='latin1')  # Try 'latin1' or 'iso-8859-1' if UTF-8 fails
demo

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDAGEMN,RIDRETH1,RIDRETH3,RIDEXMON,RIDEXAGM,...,DMDHRGND,DMDHRAGZ,DMDHREDZ,DMDHRMAZ,DMDHSEDZ,WTINT2YR,WTMEC2YR,SDMVSTRA,SDMVPSU,INDFMPIR
0,130378.0,12.0,2.0,1.0,43.0,NaN,5.0,6.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,50055.450807,54374.463898,173.0,2.0,5.00
1,130379.0,12.0,2.0,1.0,66.0,NaN,3.0,3.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,29087.450605,34084.721548,173.0,2.0,5.00
2,130380.0,12.0,2.0,2.0,44.0,NaN,2.0,2.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,80062.674301,81196.277992,174.0,1.0,1.41
3,130381.0,12.0,2.0,2.0,5.0,NaN,5.0,7.0,1.0,71.0,...,2.0,2.0,2.0,3.0,NaN,38807.268902,55698.607106,182.0,2.0,1.53
4,130382.0,12.0,2.0,1.0,2.0,NaN,3.0,3.0,2.0,34.0,...,2.0,2.0,3.0,1.0,2.0,30607.519774,36434.146346,182.0,2.0,3.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11928,142306.0,12.0,2.0,1.0,9.0,NaN,2.0,2.0,1.0,111.0,...,1.0,3.0,3.0,3.0,NaN,11147.192563,13459.129019,176.0,1.0,2.01
11929,142307.0,12.0,2.0,2.0,49.0,NaN,4.0,4.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,69419.620456,64962.328962,181.0,1.0,NaN
11930,142308.0,12.0,2.0,1.0,50.0,NaN,2.0,2.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,32696.313477,44367.534132,183.0,2.0,1.95
11931,142309.0,12.0,2.0,1.0,40.0,NaN,2.0,2.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,30547.974564,46249.361849,176.0,1.0,3.11
11932,142310.0,12.0,2.0,2.0,80.0,NaN,3.0,3.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,32753.585494,49647.225467,187.0,2.0,5.00

In [ ]:
# Load in Files â€“ BP

bp_path = 'BPXO_L.XPT'
bp = pd.read_sas(bp_path, format='xport')
bp

,SEQN,BPAOARM,BPAOCSZ,BPXOSY1,BPXODI1,BPXOSY2,BPXODI2,BPXOSY3,BPXODI3,BPXOPLS1,BPXOPLS2,BPXOPLS3
0,130378.0,b'R',4.0,135.0,98.0,131.0,96.0,132.0,94.0,82.0,79.0,82.0
1,130379.0,b'R',4.0,121.0,84.0,117.0,76.0,113.0,76.0,72.0,71.0,73.0
2,130380.0,b'R',4.0,111.0,79.0,112.0,80.0,104.0,76.0,84.0,83.0,77.0
3,130386.0,b'R',4.0,110.0,72.0,120.0,74.0,115.0,75.0,59.0,64.0,64.0
4,130387.0,b'R',4.0,143.0,76.0,136.0,74.0,145.0,78.0,80.0,80.0,77.0
...,...,...,...,...,...,...,...,...,...,...,...,...
7796,142306.0,b'R',2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7797,142307.0,b'R',4.0,127.0,75.0,132.0,73.0,131.0,72.0,71.0,70.0,67.0
7798,142308.0,b'R',3.0,106.0,65.0,106.0,69.0,112.0,74.0,58.0,61.0,69.0
7799,142309.0,b'R',3.0,127.0,81.0,125.0,82.0,128.0,81.0,80.0,79.0,83.0
7800,142310.0,b'R',4.0,128.0,81.0,121.0,78.0,129.0,81.0,77.0,78.0,79.0

In [ ]:
# Load in Files â€“ Vitamin D Lab

vitamind_path = 'VID_L.XPT'
vitd = pd.read_sas(vitamind_path, format='xport')
vitd

,SEQN,WTPH2YR,LBXVIDMS,LBDVIDLC,LBXVD2MS,LBDVD2LC,LBXVD3MS,LBDVD3LC,LBXVE3MS,LBDVE3LC
0,130378.0,5.604213e+04,58.9,5.397605e-79,1.57,1.0,57.3,5.397605e-79,2.47,5.397605e-79
1,130379.0,3.743571e+04,60.5,5.397605e-79,1.57,1.0,58.9,5.397605e-79,3.40,5.397605e-79
2,130380.0,8.532884e+04,39.4,5.397605e-79,1.57,1.0,37.8,5.397605e-79,1.52,5.397605e-79
3,130381.0,5.397605e-79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,130382.0,5.963893e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
8722,142306.0,5.397605e-79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8723,142307.0,6.899418e+04,147.0,5.397605e-79,1.57,1.0,145.0,5.397605e-79,15.90,5.397605e-79
8724,142308.0,5.397605e-79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8725,142309.0,4.628442e+04,17.8,5.397605e-79,1.57,1.0,16.2,5.397605e-79,0.78,5.397605e-79
8726,142310.0,5.325082e+04,136.0,5.397605e-79,1.57,1.0,134.0,5.397605e-79,9.28,5.397605e-79

In [ ]:
# Load in Files â€“ Hepatitis B Lab

hepatitisb_path = 'HEPB_S_L.XPT'
hepb = pd.read_sas(hepatitisb_path, format='xport')
hepb

          SEQN       WTPH2YR  LBXHBS
0     130378.0  5.604213e+04     2.0
1     130379.0  3.743571e+04     2.0
2     130380.0  8.532884e+04     2.0
3     130381.0  5.397605e-79     NaN
4     130382.0  5.963893e+04     2.0
...        ...           ...     ...
8606  142306.0  5.397605e-79     NaN
8607  142307.0  6.899418e+04     2.0
8608  142308.0  5.397605e-79     NaN
8609  142309.0  4.628442e+04     1.0
8610  142310.0  5.325082e+04     2.0

[8611 rows x 3 columns]

In [ ]:
# Load in Files â€“ Weak/Failing Kidneys

kidneys_path = 'KIQ_U_L.XPT'
kidney = pd.read_sas(kidneys_path, format='xport')
kidney

,SEQN,KIQ022,KIQ025,KIQ005,KIQ010,KIQ042,KIQ044,KIQ052,KIQ481
0,130378.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,130379.0,2.0,NaN,2.0,2.0,1.0,2.0,2.0,2.000000e+00
2,130380.0,2.0,NaN,1.0,NaN,2.0,2.0,NaN,2.000000e+00
3,130384.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,130385.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
7804,142305.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7805,142307.0,2.0,NaN,5.0,3.0,1.0,1.0,4.0,5.397605e-79
7806,142308.0,2.0,NaN,1.0,NaN,2.0,2.0,NaN,5.397605e-79
7807,142309.0,2.0,NaN,1.0,NaN,2.0,2.0,NaN,2.000000e+00
7808,142310.0,1.0,2.0,4.0,2.0,1.0,1.0,3.0,2.000000e+00

In [ ]:
# Load in Files â€“ Minutes of Sedentary Behavior

sedbehavior_path = 'PAQ_L.XPT'
behavior = pd.read_sas(sedbehavior_path, format='xport')
behavior

,SEQN,PAD790Q,PAD790U,PAD800,PAD810Q,PAD810U,PAD820,PAD680
0,130378.0,3.000000e+00,b'W',45.0,3.000000e+00,b'W',45.0,360.0
1,130379.0,4.000000e+00,b'W',45.0,3.000000e+00,b'W',45.0,480.0
2,130380.0,1.000000e+00,b'W',20.0,5.397605e-79,b'',NaN,240.0
3,130384.0,5.397605e-79,b'',NaN,5.397605e-79,b'',NaN,60.0
4,130385.0,1.000000e+00,b'D',90.0,1.000000e+00,b'W',60.0,180.0
...,...,...,...,...,...,...,...,...
8148,142305.0,2.000000e+00,b'W',40.0,5.397605e-79,b'',NaN,480.0
8149,142307.0,3.000000e+00,b'W',15.0,5.397605e-79,b'',NaN,480.0
8150,142308.0,1.000000e+00,b'W',45.0,5.397605e-79,b'',NaN,600.0
8151,142309.0,2.000000e+00,b'D',15.0,5.397605e-79,b'',NaN,240.0
8152,142310.0,5.397605e-79,b'',NaN,5.397605e-79,b'',NaN,360.0

In [ ]:
# Load in Files â€“ Current Self-Reported Weight

weight_path = 'WHQ_L.XPT'
weight = pd.read_sas(weight_path, format='xport')
weight

          SEQN  WHD010  WHD020  WHD050  WHQ070
0     130378.0    71.0   190.0   200.0     1.0
1     130379.0    70.0   220.0   220.0     2.0
2     130380.0    60.0   150.0   165.0     1.0
3     130384.0    68.0   204.0   212.0     1.0
4     130385.0    70.0   240.0   240.0     2.0
...        ...     ...     ...     ...     ...
8496  142305.0    61.0   137.0   134.0     2.0
8497  142307.0    61.0   206.0   235.0     1.0
8498  142308.0    69.0   174.0   180.0     1.0
8499  142309.0    69.0   200.0   170.0     2.0
8500  142310.0    64.0   157.0   157.0     1.0

[8501 rows x 5 columns]

## Recoding variables

In [ ]:
# Marital Status, DMDMARTZ
demo['DMDMARTZ_binary'] = demo['DMDMARTZ'].apply(lambda x: 'Married' if x == 1 else 'Not Married')
demo['DMDMARTZ_binary']

0            Married
1            Married
2            Married
3        Not Married
4        Not Married
            ...
11928    Not Married
11929    Not Married
11930        Married
11931    Not Married
11932        Married
Name: DMDMARTZ_binary, Length: 11933, dtype: object

In [ ]:
# Education Level, DMDEDUC2
demo['DMDEDUC2_binary'] = demo['DMDEDUC2'].apply(lambda x: 'Bachelors or higher' if x == 5 else 'Less than bachelors')
demo['DMDEDUC2_binary']

0        Bachelors or higher
1        Bachelors or higher
2        Less than bachelors
3        Less than bachelors
4        Less than bachelors
                ...
11928    Less than bachelors
11929    Bachelors or higher
11930    Less than bachelors
11931    Less than bachelors
11932    Less than bachelors
Name: DMDEDUC2_binary, Length: 11933, dtype: object

## Data cleaning

In [ ]:
# Hepatitis B Lab Antibodies, LBXHBS
## Two levels
print(hepb['LBXHBS'].unique())
hepb['LBXHBS_binary'] = hepb['LBXHBS'].apply(lambda x: 'Positive' if x == 1.0 else 'Negative')
hepb ['LBXHBS'].dropna()

[ 2. nan  1.]

0       2.0
1       2.0
2       2.0
4       2.0
5       1.0
       ...
8603    2.0
8605    2.0
8607    2.0
8609    1.0
8610    2.0
Name: LBXHBS, Length: 7366, dtype: float64

In [ ]:
# Weak/Failing Kidneys, KIQ022
## Two levels
print(kidney['KIQ022'].unique())
kidney['KIQ022_binary'] = kidney['KIQ022'].apply(lambda x: 'Yes' if x == 1.0 else 'No')
kidney ['KIQ022'].dropna()

[ 2.  1. nan  9.]

0       2.0
1       2.0
2       2.0
3       2.0
4       2.0
       ...
7804    2.0
7805    2.0
7806    2.0
7807    2.0
7808    1.0
Name: KIQ022, Length: 7807, dtype: float64

In [ ]:
# Minutes of Sedentary Behavior, PAD680
## Removing 7777,9999, nan values
behavior = behavior[~behavior['PAD680'].isin([7777, 9999])]
behavior = behavior.dropna(subset=['PAD680'])
behavior['PAD680'].tail(10)

8143    120.0
8144     90.0
8145    360.0
8146    120.0
8147    360.0
8148    480.0
8149    480.0
8150    600.0
8151    240.0
8152    360.0
Name: PAD680, dtype: float64

In [ ]:
# Current Self-Reported Weight, WHD020
## Removing 7777,9999, nan values
weight = weight[~weight['WHD020'].isin([7777, 9999])]
weight = weight.dropna(subset=['WHD020'])
weight['WHD020'].tail(10)

8491    248.0
8492    169.0
8493    180.0
8494    125.0
8495    165.0
8496    137.0
8497    206.0
8498    174.0
8499    200.0
8500    157.0
Name: WHD020, dtype: float64

## Questions for Analysis

In [ ]:
# Question 1: "Is there an association between marital status (married or not married) and education level (bachelorâ€™s degree or higher vs. less than a bachelorâ€™s degree)?"

import pandas as pd

contingency_table = pd.crosstab(demo['DMDMARTZ_binary'], demo['DMDEDUC2_binary'])
print(contingency_table)

from scipy.stats import chi2_contingency

chi2, p, dof, expected = chi2_contingency(contingency_table)

print(f"Chi-square statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected frequencies:")
print(expected)

# Interpretation
if p < 0.05:
    print("Significant association between marital status and education level.")
else:
    print("No significant association between marital status and education level.")

DMDEDUC2_binary  Bachelors or higher  Less than bachelors
DMDMARTZ_binary
Married                         1631                 2505
Not Married                      994                 6803
Chi-square statistic: 1120.0262540860779
P-value: 1.4666557854707472e-245
Degrees of freedom: 1
Expected frequencies:
[[ 909.82988352 3226.17011648]
 [1715.17011648 6081.82988352]]
Significant association between marital status and education level.

In [ ]:
# Question 2: "Is there a difference in the mean sedentary behavior time between those who are married and those who are not married?"

merged_data = pd.merge(demo[['SEQN', 'DMDMARTZ_binary']], behavior[['SEQN', 'PAD680']], on='SEQN')
from scipy.stats import ttest_ind

married_sedentary = merged_data[merged_data['DMDMARTZ_binary'] == 'Married']['PAD680']
not_married_sedentary = merged_data[merged_data['DMDMARTZ_binary'] == 'Not Married']['PAD680']

t_statistic, p_value = ttest_ind(married_sedentary, not_married_sedentary)

print(f"T-statistic: {t_statistic}")
print(f"P-value: {p_value}")

# Interpretation
if p_value < 0.05:
    print("Significant difference in sedentary behavior time between married and not married individuals.")
else:
    print("No significant difference in sedentary behavior time between married and not married individuals.")

T-statistic: -3.8740971309213887
P-value: 0.0001078679819334709
Significant difference in sedentary behavior time between married and not married individuals.

In [ ]:
# Question 3: "How do age and marital status affect systolic blood pressure?"

import statsmodels.formula.api as sm
!pip install statsmodels

merged_data = pd.merge(demo[['SEQN', 'RIDAGEYR', 'DMDMARTZ_binary']], bp[['SEQN', 'BPXOSY3']], on='SEQN')
model = sm.ols('BPXOSY3 ~ RIDAGEYR + DMDMARTZ_binary + RIDAGEYR * DMDMARTZ_binary', data=merged_data).fit()
print(model.summary())

# Interpretation
if model.pvalues['RIDAGEYR'] < 0.05:
    print("Significant effect of age on systolic blood pressure.")
else:
    print("No significant effect of age on systolic blood pressure.")

Requirement already satisfied: statsmodels in /usr/local/lib/python3.10/dist-packages (0.14.4)
Requirement already satisfied: numpy<3,>=1.22.3 in /usr/local/lib/python3.10/dist-packages (from statsmodels) (1.26.4)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in /usr/local/lib/python3.10/dist-packages (from statsmodels) (1.13.1)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in /usr/local/lib/python3.10/dist-packages (from statsmodels) (2.2.2)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.10/dist-packages (from statsmodels) (0.5.6)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.10/dist-packages (from statsmodels) (24.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2024.2)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5.6->statsmodels) (1.16.0)
                            OLS Regression Results
==============================================================================
Dep. Variable:                BPXOSY3   R-squared:                       0.260
Model:                            OLS   Adj. R-squared:                  0.260
Method:                 Least Squares   F-statistic:                     875.2
Date:                Mon, 04 Nov 2024   Prob (F-statistic):               0.00
Time:                        20:34:32   Log-Likelihood:                -31310.
No. Observations:                7480   AIC:                         6.263e+04
Df Residuals:                    7476   BIC:                         6.266e+04
Df Model:                           3
Covariance Type:            nonrobust
===========================================================================================================
                                              coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------------
Intercept                                 100.2083      1.011     99.167      0.000      98.227     102.189
DMDMARTZ_binary[T.Not Married]             -0.2164      1.107     -0.195      0.845      -2.387       1.954
RIDAGEYR                                    0.4063      0.018     23.086      0.000       0.372       0.441
RIDAGEYR:DMDMARTZ_binary[T.Not Married]     0.0251      0.020      1.234      0.217      -0.015       0.065
==============================================================================
Omnibus:                      915.581   Durbin-Watson:                   2.014
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2340.492
Skew:                           0.696   Prob(JB):                         0.00
Kurtosis:                       5.361   Cond. No.                         449.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
Significant effect of age on systolic blood pressure.

In [ ]:
# Question 4: "Is there a correlation between self-reported weight and minutes of sedentary behavior?"

merged_data = pd.merge(weight[['SEQN', 'WHD020']], behavior[['SEQN', 'PAD680']], on='SEQN')

from scipy.stats import pearsonr

correlation, p_value = pearsonr(merged_data['WHD020'], merged_data['PAD680'])

print(f"Pearson correlation coefficient: {correlation}")
print(f"P-value: {p_value}")

# Interpretation
if p_value < 0.05:
  print("Significant linear relationship between self-reported weight and minutes of sedentary behavior.")
else:
  print("No significant linear relationship between self-reported weight and minutes of sedentary behavior.")

Pearson correlation coefficient: 0.1559714584645021
P-value: 1.6988498386828133e-44
Significant linear relationship between self-reported weight and minutes of sedentary behavior.

In [ ]:
# Question 5: "Is there a significant association between vitamin D deficiency and the prevalence of hepatitis B infection?"

merged_data = pd.merge(vitd[['SEQN', 'vitamin_d_deficient']], hepb[['SEQN', 'LBXHBS_binary']], on='SEQN')

contingency_table = pd.crosstab(merged_data['vitamin_d_deficient'], merged_data['LBXHBS_binary'])
print(contingency_table)

from scipy.stats import chi2_contingency

chi2, p, dof, expected = chi2_contingency(contingency_table)

print(f"Chi-square statistic: {chi2}")
print(f"P-value: {p}")
print(f"Degrees of freedom: {dof}")
print("Expected frequencies:")
print(expected)

# Interpretation
if p < 0.05:
    print("Significant association between vitamin D deficiency and hepatitis B infection.")
else:
    print("No significant association between vitamin D deficiency and hepatitis B infection.")

LBXHBS_binary        Negative  Positive
vitamin_d_deficient
Deficient                5283      1996
Sufficient               1286        46
Chi-square statistic: 356.2243226783697
P-value: 1.8695570710034755e-79
Degrees of freedom: 1
Expected frequencies:
[[5552.86854024 1726.13145976]
 [1016.13145976  315.86854024]]
Significant association between vitamin D deficiency and hepatitis B infection.